### ISSUE TITLE
FIPs stops working

### ISSUE THREAD

**Issue by jdahlblom** [DCS-Skunkworks/DCSFlightpanels#1]
There is a bug causing the FIP(s) to stop updating, at the same time FP too stops working.

**Comment by c0nnex** [comment]
What is FP?
Have you enabled the DirectOuput debugging? any exception in there?

**Comment by jdahlblom** [comment]
FP = Flightpanels

No haven't enabled debugging. Didn't know there was one. We have never 
found an error message anywhere. Not in FP, not in Windows Event Log. 
Almost as a thread just gracefully shutsdown or something. I have also 
wondered if there are HID Library compability issues.

**Comment by jdahlblom** [comment]
Have you encountered the issue while playing already? It can range from a few minutes to 30 minutes until it hits you..

**Comment by jdahlblom** [comment]
deadlocking?

**Comment by c0nnex** [comment]
HID Library: The mikeobrian repository has some flaws (just read the comments there), but it should not deadlock, unless you read the devices from the main thread.
FIP: Turn on debugging in DirectOutput (see post in eagle forum) to see if it's a DO or your problem. But if not only the FIP stops, then it smells mike a deadlock. Maybe start using a SmartLock that will detect deadlocks.... (I use something very similar to http://stackoverflow.com/a/25598699 )

**Comment by jdahlblom** [comment]
Yeah did some tests but I cannot get forward. This beats me.
