### ISSUE TITLE
New feature "Identify" is great, but doesn't clear lights when complete

### ISSUE THREAD

**Issue by ZoeESummers** [DCS-Skunkworks/DCSFlightpanels#100]
Clicking the 'Identify' button flashes the landing lights on the PZ55. However they don't clear or reset after a short time. Nor does the 'identify' act as a toggle. 

If it's going to become a toggle, then fine, when it's toggled off the lights need to go back out (or to their previous state if already coloured)

If it's not going to be a toggle and the flashing lasts for a set period of time, then they need to go back out (or to their previous state if already coloured)

**Comment by jdahlblom** [comment]
I do so that all lights go out after the process if finished.
