### ISSUE TITLE
Feature Request: Landing Lights activated by sim (if possible)

### ISSUE THREAD

**Issue by ZoeESummers** [DCS-Skunkworks/DCSFlightpanels#101]
I don't know much about DCS BIOS but I believe it is sending out the status of the aircraft gear travel / lock lights. 

If this is the case, then we need an option to have the PZ55 lights work in sync with the aircraft module.

**Comment by WarLord211** [comment]
with BIOS they work sync with the sim.(if you program them )
without not possible

**Comment by jdahlblom** [comment]
Yes, user must configure this. Each module has its own DCS-BIOS control for the lights.

**Comment by ZoeESummers** [comment]
How do you configure the lights on the PZ55 to work with say the F18 for example? 

It's unclear how to do that.

Surely if you create a new profile, and select DCS BIOS and the module e.g. F18, then the lights on the panel should be automatically set to be in sync with the sim no?

**Comment by jdahlblom** [comment]
Should be these. I don't own that module so I have no idea how it looks in the cockpit.
`defineIndicatorLight("FLP_LG_NOSE_GEAR_LT", 166, "Flaps, Landing Gear, Stores Indicator Panel", "NOSE GEAR")
defineIndicatorLight("FLP_LG_LEFT_GEAR_LT", 165, "Flaps, Landing Gear, Stores Indicator Panel", "LEFT GEAR")
defineIndicatorLight("FLP_LG_RIGHT_GEAR_LT", 167, "Flaps, Landing Gear, Stores Indicator Panel", "RIGHT GEAR")`

They are configured in this profile:
https://github.com/DCSFlightpanels/DCSFlightpanels-Profiles/blob/master/FA-18C/Flight%20Panel%20FA18-C%20(VirusAM).bindings

**Comment by ZoeESummers** [comment]
So are you saying that I have to right click on each light on your graphical representation of the PZ55 switch panel, and then set a DCSBIOS hook for it? 

This is what I'm trying to explain. If this is the case - that's not obvious. Perhaps more obvious is if you specify which module your profile is using, it will do these bindings for your if the 'manual lights' box is un-ticked. 

If you want to make users do it, then perhaps explaining how would be better as I've been using this software for years and I didn't know (and still don't) how to do it.

**Comment by jdahlblom** [comment]
Yes is the short answer.
There are videos showing how to use DCS-BIOS on the front page. OK so there should be some kind of a tip for the user that they can be configured.
