### ISSUE TITLE
Numbers after comma in radio panel

### ISSUE THREAD

**Issue by epalzeolithe** [DCS-Skunkworks/DCSFlightpanels#104]
Hi i use generic radio panel to show informations,

i put formulas for LCD display, but i can't only show integers, i cant have numbers after comma, hos is it possible ? Thanks

**Comment by jdahlblom** [comment]
Can you share your profile, perhaps better you DM me at our Discord server.

**Comment by jdahlblom** [comment]
Did you solve this?
