### ISSUE TITLE
F18 radio panel issue

### ISSUE THREAD

**Issue by epalzeolithe** [DCS-Skunkworks/DCSFlightpanels#106]
Hi you did a real good job

well i've got an issue on F18 module, radios/channels are displayed well, but the knobs dont change anything (volume or channel)

is there a fix ?

Thanks !

**Comment by WarLord211** [comment]
Bios version?

**Comment by jdahlblom** [comment]
https://github.com/DCSFlightpanels/DCSFlightpanels/wiki/Creating-Github-Issue(s)-(bug-reports---feature-requests)

**Comment by WarLord211** [comment]
Duplicate of #75

**Comment by WarLord211** [comment]
Have you tryed the prerelease  4.2.10 ?
