### ISSUE TITLE
StreamDeck not detected

### ISSUE THREAD

**Issue by epalzeolithe** [DCS-Skunkworks/DCSFlightpanels#107]
StreamDeck not detected

i tried with official steam deck app not running, and running, both.

It detects well my saitek panel, but not the stream deck

Is it normal ?

**Comment by jdahlblom** [comment]
It is really hard to say what is the issue. Try and connect it directly to the PC.

**Comment by jdahlblom** [comment]
It should detect the Streamdeck just as it detects the Saitek panels.
