### ISSUE TITLE
Radio Panel PZ69 does not work on Spitfire and P-47D.

### ISSUE THREAD

**Issue by Saylors** [DCS-Skunkworks/DCSFlightpanels#114]
I also found out that the DCSFlightpanels_x64_4.2.16 has Radio Panel PZ69 for P-47D working (but not yet in the P-47D cockpit itself in DCS). And Radio Panel PZ69 for Spitfire does not work.
![PZ69 (P-47D)](https://user-images.githubusercontent.com/50142231/111763456-384c9a80-88b3-11eb-9ecf-1927beb1a1ac.PNG)
![PZ69 (Spitfire LF Mk IX)](https://user-images.githubusercontent.com/50142231/111763479-3edb1200-88b3-11eb-930e-e4b37863ad00.PNG)
![PZ69 (P-51D)](https://user-images.githubusercontent.com/50142231/111763702-7c3f9f80-88b3-11eb-94ef-64364eeda679.PNG)

**Comment by jdahlblom** [comment]
Did these radios work before?

**Comment by Saylors** [comment]
It worked just as well on the Spitfire before (sometime in the summer of 2020) as it did on the P-51D. I don't know about the P-47D.

**Comment by jdahlblom** [comment]
I can not test P-47D as I don't have that module. The radio is supposed to be exactly the same as Spitfires so it is a copy of that.

**Comment by Saylors** [comment]
On the Spitfire in the cockpit worked as before - thank you very much!
On the P-47D the PZ69 panel works in DCSFlightpanels_x64_4.2.18, but not in the cockpit of the P-47D.
What can I do for the P-47D? What files can I provide?

**Comment by Saylors** [comment]
Did an experiment - ran a Spitfire profile in the cockpit of a P-47D. And some elements work (except channel switching) - on the profile from P-47D elements of the radio in the cockpit of P-47D do not work. 
I made screenshots of the commands, maybe it will be useful:

![Снимок](https://user-images.githubusercontent.com/50142231/111785196-57f0bc80-88cd-11eb-89b4-c62803bbb222.PNG)
![1](https://user-images.githubusercontent.com/50142231/111785364-91292c80-88cd-11eb-8baa-25f525969232.PNG)
![2](https://user-images.githubusercontent.com/50142231/111785378-95554a00-88cd-11eb-8900-68b69680b3fb.PNG)
![3](https://user-images.githubusercontent.com/50142231/111785393-9a19fe00-88cd-11eb-8560-5179f504e601.PNG)
![4](https://user-images.githubusercontent.com/50142231/111785419-a30acf80-88cd-11eb-9b8e-b49cabab6c2c.PNG)
![5](https://user-images.githubusercontent.com/50142231/111785493-ba49bd00-88cd-11eb-90cd-a520aa8329ac.PNG)
![6](https://user-images.githubusercontent.com/50142231/111785569-d3eb0480-88cd-11eb-9ef6-0fe65c50bf0f.PNG)
![7](https://user-images.githubusercontent.com/50142231/111785582-d9484f00-88cd-11eb-81a8-cd2523ff0557.PNG)
![8](https://user-images.githubusercontent.com/50142231/111785595-de0d0300-88cd-11eb-967f-6024ec9229b5.PNG)
![9](https://user-images.githubusercontent.com/50142231/111785612-e2392080-88cd-11eb-826c-23dbe70e1691.PNG)
![10](https://user-images.githubusercontent.com/50142231/111785627-e6fdd480-88cd-11eb-86b0-fecf3830f8be.PNG)
![11](https://user-images.githubusercontent.com/50142231/111785645-ebc28880-88cd-11eb-9c42-55f311fb3722.PNG)
![12](https://user-images.githubusercontent.com/50142231/111785661-ef560f80-88cd-11eb-8faa-82cbaa0b00dc.PNG)
![13](https://user-images.githubusercontent.com/50142231/111785672-f2e99680-88cd-11eb-8110-b6edb3f1482d.PNG)

**Comment by jdahlblom** [comment]
Is Spitfire working? 
I can't do much more as it for P-47D. It is super difficult implementing when I can't debug what I am doing. You can donate via the Wiki page so I can purchase the P-47D.

**Comment by Saylors** [comment]
Yes - the Spitfire radio partially works in the cockpit of the P-47D.
Ok. I gave as much as I could to both you and Warlord (he helped fix the Bios for the profiles). Thanks for all your help - did a lot. 
I'm from Russia.

**Comment by jdahlblom** [comment]
@Saylors  Thanks for the donation Saylors(!) Warlord also shared his donation => I managed to get the module.
Try this : https://github.com/DCSFlightpanels/DCSFlightpanels/releases/tag/4.2.19
It is working properly?

**Comment by Saylors** [comment]
Hi!
No, everything is the same - the radio does not work in the cockpit of P-47D (profile from P-47D).
On the profile from Spitfire some elements of the radio in the cockpit of the P-47D work (as in the screenshots above).
Checked with DCSFlightpanels_x64_4.2.19.
For example my profiles for the P-47D and the Spitfire:



[Flight Panel P-47D & Spitfire.zip](https://github.com/DCSFlightpanels/DCSFlightpanels/files/6176169/Flight.Panel.P-47D.Spitfire.zip)

**Comment by jdahlblom** [comment]
I have updated to 4.2.27, all support libraries have been updated. I don't understand, the 4.2.19 worked for me. I will ask Warlord to also test.
Just to be sure, delete the old settings as instructed in "Settings" and then try again.

**Comment by jdahlblom** [comment]
Warlord says the P-47D radio now works.

**Comment by WarLord211** [comment]
from BIOS side! not tested with flight panels!

**Comment by Saylors** [comment]
I did as you wrote above - it works! 
In the profile now changed 2 lines - 
**EmulationModesFlag=3
UseGenericRadio=False**

It used to be like this: 
**OperationLevelFlag=3
UseGenericRadio=True**
![Безымянный](https://user-images.githubusercontent.com/50142231/111914085-b363ab80-8a81-11eb-85d3-76d1180fde1d.png)


Now, when creating new profiles, should the Use Generic Radio Panel be unchecked?
![3](https://user-images.githubusercontent.com/50142231/111914101-c0809a80-8a81-11eb-8082-ccae131bee29.PNG)

**Comment by Saylors** [comment]
Yes - I checked with the P-51D and Spitfire profiles with the Use Generic Radio Panel unchecked. The checkbox must be checked when the user wants to program the radio panel himself (I didn't know that before).
Thank you very much for your help.
