### ISSUE TITLE
Minimize to SystemTray not working

### ISSUE THREAD

**Issue by WarLord211** [DCS-Skunkworks/DCSFlightpanels#117]
From ED Forums:

_Hi. On Options/Settings window, I click "Minimize To System Tray", but it won't do that.

I deleted AppData folders. I re-saved my commandkeys etc. etc., but everytime I check Settings, "Minimize" option seems unchecked (or not saved)._
https://forums.eagle.ru/topic/115280-dcsflightpanels-dcsfp-thread-saitek-pro-flight-panels-amp-dcs/?do=findComment&comment=4629649

Tested on my end too. with same results. Checkbox not saved. (not in user or admin mode)

**Comment by jdahlblom** [comment]
Check https://github.com/DCSFlightpanels/DCSFlightpanels/releases/tag/4.2.30

**Comment by WarLord211** [comment]
works again. Thank you!
