### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by DDbrico** [DCS-Skunkworks/DCSFlightpanels#118]
Hello,

  With version 4.2.6 of DCSFlightpanels I have no operating error, but from versions 4.2.10 and above it is impossible for me to save the location of DCS-BIOS version 0.7.39a.
  Whatever the version of DCS-BIOS, the result is the same.
  DCS-BIOS works and returns the values, checked in the browser.
  The checks on the "Troubleshooting" page did not yield anything.
  DCSFlightpanels is in administrator mode, Windows is up to date 20H2 19042.928 as well as DCS 2.7.0.5118.
  The installation directory of DCSFlightpanels as well as the exe are declared in the Windows antivirus.
 
  When I run version 4.2.6, without changing anything, it works without problem.
  I did not find a solution in the various pages of the eagle forum and here.
 
  here is what I get in the log:

26.04.2021 04:57:10  version : 1.0.324.6091

System.NullReferenceException
La référence d'objet n'est pas définie à une instance d'un objet.
   à DCSFlightpanels.MainWindow.SetWindowTitle()
   à DCSFlightpanels.MainWindow.CreateNewProfile()
   à DCSFlightpanels.MainWindow.WindowLoaded(Object sender, RoutedEventArgs e)

26.04.2021 04:57:06  version : 1.0.324.6091

System.NullReferenceException
La référence d'objet n'est pas définie à une instance d'un objet.
   à NonVisuals.ProfileHandler.SetEmulationModeFlag()
   à NonVisuals.ProfileHandler.set_Profile(DCSFPProfile value)
   à NonVisuals.ProfileHandler.LoadProfile(String filename, IHardwareConflictResolver hardwareConflictResolver)
 
  If you have a solution, I'm interested.
  I remain at your disposal and wish you a good day.
  cordially,
Didier

**Comment by WarLord211** [comment]
the folder cleared in ....\AppData\Local\DCSFlightpanels ?

**Comment by DDbrico** [comment]
Yes all files relating to DCSFlightpanels.
Strangely version 4.2.6 older versions work.
I don't know what may have changed with version 4.2.10 but with this version and later I cannot save the path to DCSBios. Even after changing the read / write rights of the files.
Have a good day

**Comment by DDbrico** [comment]
Hello, I think I have found the cause of my troubles.
The error message is caused by the previous profile loaded with version 4.2.6.
In the new profiles the lines "Airframe = FA18C" and "OperationLevelFlag = 3" are replaced by "Profile = 20" and "EmulationModesFlag = 3".
If you want to use the old profiles, all you have to do is create a blank profile for the module concerned, then edit it in order to copy these lines, and then replace them in the old profile.
Thanks for your help,
have a good day.
Sincerely Didier

**Comment by jdahlblom** [comment]
Hi,
Glad you found the problem although I did intend for DCSFP to fix this. So this is a bug. There shouldn't be any need for the user to make changes. I will check.

**Comment by DDbrico** [comment]
The problem therefore stems from a bug, happy to have the confirmation that it was not located between the back of my chair and the keyboard ;) Have a good day
