### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by SoulMaril** [DCS-Skunkworks/DCSFlightpanels#119]
I am getting this error when ever I try to open a profile:
Object reference not set to an instance of an object

can't find a way to solve it. I will be glad if anyone helps.

**Comment by SoulMaril** [comment]
I don't have a path like this anymore
..Users\<username>\Saved Games\DCS\Scripts\DCS-BIOS\doc

DCS-BIOS hub do not install such directory.

Do I have to install the fork of DCS-BIOS from here?

**Comment by SoulMaril** [comment]
Installed 0.7.40 Fork but same error.

**Comment by WarLord211** [comment]
.......\Saved Games\DCS\Scripts\DCS-BIOS\doc\json

should the correct path for the Fork BIOS.
HUB should generate a folder  with json files in .....\Saved Games\DCS\DCS-BIOS

**Comment by SoulMaril** [comment]
I manually extracted the fork (DCS BIOS 0.7.40) like this ..\Saved Games\DCS\Scripts\DCS-BIOS\doc\json
I installed the HUB but I don't have this ..\Saved Games\DCS\DCS-BIOS

**Comment by DDbrico** [comment]
Hello, At any risk, test the solution that I describe in post # 118
Sincerely, Didier

**Comment by jdahlblom** [comment]
Check https://github.com/DCSFlightpanels/DCSFlightpanels/releases/tag/4.2.30
