### ISSUE TITLE
Json directory wont save in Settings

### ISSUE THREAD

**Issue by Skybad007** [DCS-Skunkworks/DCSFlightpanels#120]
4.2.27.6092 Tried pointing to the json directory within flight panel PZ55 and it wont save. I have run DCS BIOS control ref and that sees DCS when i get into a mission but the panel and DCS BIOS will not communicate with each other. I can use either or in DCS and both work independently.

**Comment by WarLord211** [comment]
HUB or FP BIOS?

**Comment by Skybad007** [comment]
FP Bios

**Comment by DDbrico** [comment]
Hello, At any risk, test the solution that I describe in post # 118
Sincerely, Didier

**Comment by jdahlblom** [comment]
Check https://github.com/DCSFlightpanels/DCSFlightpanels/releases/tag/4.2.30

**Comment by DDbrico** [comment]
Hello, I confirm the resolution of the bug corresponding to post # 118 by version 4.2.30.
Thank you again, have a nice day.
Didier
