### ISSUE TITLE
(Key Emulation) Keypress Stuck When Using Gear Lever

### ISSUE THREAD

**Issue by ghost** [DCS-Skunkworks/DCSFlightpanels#123]
Hi,

I tried this in Versions 4.2.27 and 4.2.30 using Key Emulation mode.

I'm Working on setting this up and noticed that if I assign a key to Gear Down or Gear Up and set it to indefinite, the keyboard button is held properly but is held indefinitely even if the lever has changed position, this happens until the application is exited.

```
PanelType=PZ55SwitchPanel
PanelInstanceID=\\?\hid#vid_06a3&pid_0d67#9&c8408b0&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
BindingHash=82a82ba63216b53a9761a57bb89e3e59
BeginPanel
	SwitchPanelKey{1SWITCHKEY_LIGHTS_LANDING}\o/OSKeyPress{Indefinite,VK_L}
	SwitchPanelKey{0SWITCHKEY_LIGHTS_LANDING}\o/OSKeyPress{ThirtyTwoMilliSec,VK_NULL}
	SwitchPanelKey{1LEVER_GEAR_DOWN}\o/OSKeyPress{Indefinite,VK_L}
	SwitchPanelKey{1LEVER_GEAR_UP}\o/OSKeyPress{ThirtyTwoMilliSec,VK_NULL}
	ManualLandingGearLEDs{True}
EndPanel
```
I found that adding a 0LEVER_GEAR_DOWN line fixes my problem.
```
PanelType=PZ55SwitchPanel
PanelInstanceID=\\?\hid#vid_06a3&pid_0d67#9&c8408b0&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
BindingHash=82a82ba63216b53a9761a57bb89e3e59
BeginPanel
	SwitchPanelKey{1SWITCHKEY_LIGHTS_LANDING}\o/OSKeyPress{Indefinite,VK_L}
	SwitchPanelKey{0SWITCHKEY_LIGHTS_LANDING}\o/OSKeyPress{ThirtyTwoMilliSec,VK_NULL}
	SwitchPanelKey{1LEVER_GEAR_DOWN}\o/OSKeyPress{Indefinite,VK_L}
	SwitchPanelKey{0LEVER_GEAR_DOWN}\o/OSKeyPress{ThirtyTwoMilliSec,VK_NULL}
	SwitchPanelKey{1LEVER_GEAR_UP}\o/OSKeyPress{ThirtyTwoMilliSec,VK_NULL}
	ManualLandingGearLEDs{True}
EndPanel
```
However this fix causes another issue where every time I try to assign another key, it will throw an error `Failed to find text box based on key`.

![Screenshot 2021-06-29 200200](https://user-images.githubusercontent.com/75815701/123886410-fd77eb00-d914-11eb-9f06-3b54f361f6b8.png)

**Comment by jdahlblom** [comment]
Please check : https://github.com/DCSFlightpanels/DCSFlightpanels/wiki/Emulating-a-key-being-pressed-down-continuously

Is that what you need (VKNULL)?

**Comment by jdahlblom** [comment]
I will check this now.

**Comment by jdahlblom** [comment]
@YarboughJR Please close this issue if problem is fixed in latest release.

**Comment by ghost** [comment]
@jdahlblom I can confirm the latest release has fixed this issue, thank you for the quick response.
