### ISSUE TITLE
PZ69 support for enabling/disabling radios

### ISSUE THREAD

**Issue by stouset** [DCS-Skunkworks/DCSFlightpanels#13]
It would be fantastic if a long press of the standby/active switch would switch radios on and off (including TACAN, perhaps just rotating between Off, T/R, and A/A T/R?)

**Comment by jdahlblom** [comment]
Specifically for the A-10C?

**Comment by stouset** [comment]
A-10C, yep. It's great to be able to switch freqs, but also being able to turn radios on/off would be extremely useful. Long-press of the active<->standby button could just cycle the knobs for UHF/VHF AM/VHF FM/ILS/TACAN.

**Comment by jdahlblom** [comment]
Okay, yes it would be possible as long as it doesn't remove existing functionality.

**Comment by jdahlblom** [comment]
You can check the latest release.

**Comment by jdahlblom** [comment]
Now you can turn of VHF AM FM and UHF in A-10C.
