### ISSUE TITLE
m2000c VHF/UHF/VOR is minor -1 than DCS cockpit

### ISSUE THREAD

**Issue by shan-aya** [DCS-Skunkworks/DCSFlightpanels#133]
hi,
in m2000c
VHF & UHF is 4 on cockpit preset but 3 in saitek

VOR is 108.25 on cockpit but 107.25 in saitek

**Comment by jdahlblom** [comment]
Are you using latest DCS-BIOS & DCSFP?
Official DCS or openbeta?

**Comment by shan-aya** [comment]
yes lastest dcs-bios& dcsfp (master branch )
and openbeta 
i check this with warlord for dcs-bios issue but it say that's more a dcsfp issue

**Comment by jdahlblom** [comment]
OK, confirmed. I have informed @WarLord211 about this as the CTRL-Ref  actually also shows the wrong value.
VOR-ILS was a DCSFP bug.

**Comment by jdahlblom** [comment]
Check latest release and close issue if problem is fixed.

**Comment by shan-aya** [comment]
yes it works perfectly ! thx
