### ISSUE TITLE
REQUEST : adding frequencies in m2000c left radio panel

### ISSUE THREAD

**Issue by shan-aya** [DCS-Skunkworks/DCSFlightpanels#134]
hi,
if possible to adding frequencies from radio preset in left screen radio panel ?
thx

**Comment by jdahlblom** [comment]
Do you mean COM1 & COM2 when having preset channels? Showing the frequency?

**Comment by jdahlblom** [comment]
I have been testing with latest DCSFP & DCS-BIOS. It seems broken. It shows only "1" in the left display. Is this what you mean? That is a bug?

**Comment by shan-aya** [comment]
yes in the dedicated radio panel for m2000
i find argument in dcs-bios but it is not present in dcsfp  : M-2000C/UHF_FREQUENCY & M-2000C/VHF_FREQUENCY
and i can't access to dedicated module radio :) ( not prrogramming skill enough :) )

**Comment by jdahlblom** [comment]
OK. Fixed. The frequency will show in the right LCD and channel in left LCD. Will release as soon as I know more about #133 . Warlord will check.

**Comment by jdahlblom** [comment]
Check latest release and close issue if problem is fixed.

**Comment by shan-aya** [comment]
sorry but i'm not familiar with source for compile x64 version :(
no x64 version in asset 
thx

**Comment by WarLord211** [comment]
exe was missing. is now uploaded

**Comment by shan-aya** [comment]
great ! it works perfectly :)
i complete my profile with formula for multi panel ( speed, mach ..etc) and i post it
