### ISSUE TITLE
PZ69 support for radio presets

### ISSUE THREAD

**Issue by stouset** [DCS-Skunkworks/DCSFlightpanels#14]
It would also be great if the software could detect whether or not you've selected preset channels for a given radio, and allow you to select between them.

**Comment by jdahlblom** [comment]
Do you refer to DCS-BIOS or SRS?

**Comment by stouset** [comment]
Specifically, using the flight panels through SRS. My squadron uses presets heavily for intra-flight comms, CTAF, etc. It would be useful if SimpleRadio could tell when the knob for UHF/VHF radios are set to use preset instead of manual, and view and allow changing which preset is being selected (rather than just adjusting the manual frequency).

**Comment by jdahlblom** [comment]
Hmm, I have to check that. It should be that if you have presets selected in SRS, DCSFP should then up/down these, not frequencies.

**Comment by jdahlblom** [comment]
Are you referring to FC3 modules now, using SRS? Because when it is a DCS-BIOS module it is not possible at the moment. I found a bug in DCSFP SRS code.
If you were in SRS PRESET mode and turned the small radio dial then SRS switched over to using FREQ. This I have fixed.

**Comment by jdahlblom** [comment]
Created a release with this fix + others.

**Comment by stouset** [comment]
I'm unfamiliar with the SRS presets you're talking about—we may be referring to the same thing or speaking past one-another.

I primarily fly the A-10C, and the VHF/UHF radios can either use manually-set frequencies or use preprogrammed frequencies via a separate dial. I'd like the software to detect when a given radio is in manual or preset mode. In manual mode it should work as it does currently, but when in preset mode the panels should show the current preset (e.g., 3) and allow cycling the preset knob up or down.

I'll test this release and see if it does what I'm hoping for :)

**Comment by jdahlblom** [comment]
OK, then it isn't working at the moment (A-10C). But is doable and sensible. I'll have a look at the DCS-BIOS profile for this.

**Comment by jdahlblom** [comment]
It seems that it is these controls that shows whether the radio is in PRESET:
VHFFM_FREQEMER
VHFAM_FREQEMER
UHF_MODE
and these controls holds the channel:
VHFAM_PRESET
VHFFM_PRESET
UHF_PRESET_SEL

I'll fix this.

**Comment by jdahlblom** [comment]
You can check the latest release.

**Comment by stouset** [comment]
Thanks for all your hard work!
