### ISSUE TITLE
F/A-18C support

### ISSUE THREAD

**Issue by stouset** [DCS-Skunkworks/DCSFlightpanels#15]
Just adding these as placeholders. I'm not sure if this is being actively maintained any more.

**Comment by jdahlblom** [comment]
Sorry, I don't own the DCS module, I think there is a DCS-BIOS profile for it though.

**Comment by stouset** [comment]
If there is, what's the level of effort required to implement support (and would you accept patches)?

**Comment by jdahlblom** [comment]
Well, first of all you want to make sure it works manipulating the radios (as you want, need to) via the DCS-BIOS CTRL-Ref page. If that works OK then create new classes for this airframe. Lots and lots of code exists already so it usually boils down to copy/paste and change here and there.
If you want to do it I'd be more than happy to help you out. It would be very good to have someone else to help out with coding.

**Comment by stouset** [comment]
I'll give it a shot when I have some time.

**Comment by stouset** [comment]
I'll give it a shot when I have some time.

**Comment by jdahlblom** [comment]
Added in latest pre release.
