### ISSUE TITLE
F-5E support

### ISSUE THREAD

**Issue by stouset** [DCS-Skunkworks/DCSFlightpanels#16]

**Comment by jdahlblom** [comment]
Sorry, don't own that. Don't know whether there is a DCS-BIOS module for it.

**Comment by stouset** [comment]
No worries. Just opened this as a tracking issue.

**Comment by jdahlblom** [comment]
Support added, radio not implemented yet. DCS-BIOS profile being extended.

**Comment by WarLord211** [comment]
F-5E support now complete
