### ISSUE TITLE
Version info in about dialog

### ISSUE THREAD

**Issue by emcek** [DCS-Skunkworks/DCSFlightpanels#18]
It will be nice to know which version I'm running. Additionally it could check if new version is available.

**Comment by jdahlblom** [comment]
Check this release : https://github.com/DCSFlightpanels/DCSFlightpanels/releases/tag/2.7.1
It shows the version info in the bottom of the main window on the left side.

**Comment by emcek** [comment]
Nice! When next new release come I will check if I got notification. Well done!
