### ISSUE TITLE
One more check for DCS-BIOS

### ISSUE THREAD

**Issue by emcek** [DCS-Skunkworks/DCSFlightpanels#19]
Hmmm... I was thinking it its good idea during checking new version of flight panel, may be It is possible to check DCS-BIOS as well.
I'm not sure DCS-BIOS can check itself for new release (and even so I can be tricky to let end user know), so maybe FlightPanel could done it.
But as far I know DCB-BIOS does not provide any version marker in its files. So we need some variable or comment in i.e. here: [BIOS.lua](https://github.com/DCSFlightpanels/dcs-bios/blob/f23c810b7f95cef008a5b1907a9aec0416bd8844/Scripts/DCS-BIOS/BIOS.lua#L1)

What you think?

**Comment by jdahlblom** [comment]
Yeah it would be good. But I can say directly, having to change version number manually each time is not a good idea. Perhaps I could check for the latest release and write something "Last DCS-BIOS released X days ago". What do you think?

**Comment by jdahlblom** [comment]
Manually changing version numbers => there is a 99.9% change you forget to update it.

**Comment by jdahlblom** [comment]
Alright, check latest release. It has the DCS-BIOS release date info added to the status bar.

**Comment by emcek** [comment]
You are my god! 
btw. I want test FlightPanels version checking. Right now I'm on v2.7.1.57.13 after start nothing happens. How FlightPanel notify about new pre-release?

**Comment by jdahlblom** [comment]
Your version checks once a day for a new version. Older versions checks every 3 days. Don't know whether it makes any difference but at some point when I was developing something and had it checking at every startup I got error messages from Github about that. Don't remember exact message but something about quota exceeded.

**Comment by jdahlblom** [comment]
v2.7.1.57.13? You must be in the future.

**Comment by emcek** [comment]
![image](https://user-images.githubusercontent.com/475312/47458306-812ec080-d7d9-11e8-9809-59dcb1ea9ad6.png)

**Comment by emcek** [comment]
> ... and had it checking at every startup I got error messages from Github about that. Don't remember exact message but something about quota exceeded.

Probably GitHub limit traffic, question is, it is per installation (every end user has quota) or per project (you organization DCSFlightpanels has quota). Any way, form me even 1 week is good enough. I will wait another 1 or 2 day it check if I got notification form 2.7.1 that 2.7.4 is available.

**Comment by jdahlblom** [comment]
Yeah sounds reasonable. Btw did it (is it) working? I garbled your version numbers when I read them, yes the version number was OK.

**Comment by emcek** [comment]
hmmm... plug panels to USB and load some profile, in DCSFlightpanels_error_log.txt got (i'm on 2.7.1):
```
26.10.2018 09:54:18  version : 1.0.98.5712
2000 Message = [Below is a list of duplicate identifiers found in the Ka-50.json profile (DCS-BIOS)
The identifier must be unique, please correct the profile Ka-50.lua in the DCS-BIOS lib folder
---------------------------------------------
ADI_PITCH
ADI_ROLL
ADI_YAW
---------------------------------------------
]
```

**Comment by jdahlblom** [comment]
Yes I can correct it. It is just that those controls are entered in duplicate in the Ka50.lua file.

**Comment by jdahlblom** [comment]
https://github.com/DCSFlightpanels/dcs-bios/releases/tag/0.7.15
