### ISSUE TITLE
Hold key not working

### ISSUE THREAD

**Issue by Samino2** [DCS-Skunkworks/DCSFlightpanels#42]
Hi,
When I try the hold key option I think he press multiple time.
I use the pannel with Star Citizen, I know its not made for it but when I need to press for one second a key he execute the commend when I press and release the key (example I just go out of the chair and don't eject).

Thanks ^^'

**Comment by jdahlblom** [comment]
Has it worked with previous versions of DCSFP? 
It works by sending a stream of Key "x" events when you hold down a button. It differs then how the program interprets it. Windows key API:s are little of a jungle imho. 
Have you tried the other Windows API, you can select it from the Settings menu.

**Comment by jdahlblom** [comment]
So you keep the key pressed but Star Citizen interprets it like a single key press?

**Comment by Samino2** [comment]
I think, I use the Ctrl buttons for the assign who need to stay press like the quantum travel and the ejection, but if I use another key it's don't work

**Comment by jdahlblom** [comment]
Yup, tried SHIFT + A (continuous) and it produces only small "aaaaaaaaa". I will investigate.

**Comment by jdahlblom** [comment]
I did a new compile, didn't really make any changes to the actual Windows API call. Anyways I can now produce AAAAAAAAAAAA using the "Keep pressed" option. Try the latest release. Wonder if this was some kind of fluke error? I hope so. :)

**Comment by jdahlblom** [comment]
Is a bit hard testing CTRL+Key, don't know how to verify it. Shift+Key is easy.

**Comment by Samino2** [comment]
Okay =) thanks a lot, I will try it Sunday ^^

**Comment by Samino2** [comment]
Hi I am sorry but how to download the new compil?

**Comment by Samino2** [comment]
I think is not working, when I use the hold shif+a key its work on the pannel but in game its not working

**Comment by jdahlblom** [comment]
OK. I have to check what the hell differs between and event made by DCSFP and that of a keyboard key press.

**Comment by jdahlblom** [comment]
I think I found something that could be the problem using Spy++. Can you head over to our Discord server and I will share a link to you where you can find the test version. I don't want to make release for this.
https://discord.gg/5svGwKX

**Comment by jdahlblom** [comment]
My nick is ArturDCS.

**Comment by jdahlblom** [comment]
I spent more than 1h to make a fix, to find what could be wrong and you don't care testing it?

**Comment by Samino2** [comment]
Sorry I just have bigs problem in this time, I am really sorry about that, I can have my computer only 4/5 day ^^' I am really sorry

**Comment by jdahlblom** [comment]
OK still not working. I will have a look at it again. Can't figure it out straight away as Spy++ showed same Windows messages now between keyboard and DCSFP. But I will look at it again.

**Comment by jckaboom** [comment]
got the quantum to work on star citizen.
with default key set to "b" in game
in DCSFlightpanels set "Panel On" to "VK_B" at ThirtyTwoMilliSec (32ms)
in DCSFlightpanels set "Panel Off" to "VK_B" at Second (1sec)
and done.
Log for reference: 
bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb2. VK_B
b2. VK_B

**Comment by jdahlblom** [comment]
@jckaboom Did you get it to work also with using VKNULL? Missed your post here.

**Comment by jdahlblom** [comment]
https://github.com/DCSFlightpanels/DCSFlightpanels/wiki/Emulating-a-key-being-pressed-down-continuously
