### ISSUE TITLE
Not Running

### ISSUE THREAD

**Issue by Mooch982** [DCS-Skunkworks/DCSFlightpanels#43]
I have been using Flightpanels for a long time, suddenly it refuses to start, it will appear momentarily in the hidden icons tray but I cannot get it to run, deleted and redownloaded numerous times, allowed firewall exceptions etc all with no joy.

**Comment by jdahlblom** [comment]
What does Windows Event Logs report?

**Comment by Mooch982** [comment]
Microsoft-App-V-Client/Operational Overwrite evens as necessary

**Comment by jdahlblom** [comment]
What Windows version are you using?

**Comment by jdahlblom** [comment]
Btw have you checked with the users @ Discord? They could very well solve this for you.

**Comment by jdahlblom** [comment]
Can I close this issue?

**Comment by Mooch982** [comment]
Of course, didn't really go anywhere

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________
