### ISSUE TITLE
High CPU load when connection to panel lost

### ISSUE THREAD

**Issue by emcek** [DCS-Skunkworks/DCSFlightpanels#44]
I noticed minor problem with scenerio, I have panels connected via HUB USB RaidSonic IcyBox 7 where each has a on/off switch:
- all 3 panels are connected and switch turned on
- start DCSFlightpanels, no problem everything working wit DCS
- turn switches off / disconnect panels (don't really matter if DCS is on or off)
- DCSFlightpanels use ~40% CPU
- turn switches on / connect panels
- load back to normal

Probably there is some polling of searching for device which cause so high load but since it isn't proper way of using I thing is a minor issue. 

But I thing you can tak a look and see some optimization when connection to panel is lost.

**Comment by jdahlblom** [comment]
DCSFP does not handle attach detach of devices. I had it at some point but removed it for some reason.  I don't remember any more but is this an issue? How often does this happen with healty H/W?

**Comment by emcek** [comment]
hmmm... it is not really a issue just observation... if I follow steps it happens every time... to be honest probably nobody will start DCSFP without panels connected ;)

**Comment by jdahlblom** [comment]
Do you mean that if you unplug before starting DCSFP or while DCSFP is running?

**Comment by emcek** [comment]
unplug panels while DCSFP is working

**Comment by jdahlblom** [comment]
Yeah OK. I have to think about it. I have this vague memory I had a lot of problems with attaching and detaching panels, there is a lot going on in the background and DCSFP had problems reacting properly.
It isn't supposed to be like that - to be clear. At the moment though there are more pressing issues. But this issue can stay so I won't forget it.

**Comment by emcek** [comment]
Yes, lets keep it open to track issue and agreed it is not top blocker at the moment. 

In general it looks like common problem of dead connection - how often check/detect if device is connected back or how long keep context in case just minor connection problem.

As I said, I belie just small users disconnect panel device while DCSFP is working and even so they probably connected it back. So, nobody noticed this behavior.

**Comment by jdahlblom** [comment]
Next release will have graceful panel detachment.
