### ISSUE TITLE
M2000C Radio panel

### ISSUE THREAD

**Issue by Nishizawa145** [DCS-Skunkworks/DCSFlightpanels#45]
Hello, are you going to update the M2000C radio profile? After last Razbam`s patch there is no more possibility to tune green radio, ILS or TACAN.
Greetngs!

**Comment by jdahlblom** [comment]
Yes I will update it. I have to check what changes has been made.

**Comment by jdahlblom** [comment]
Do you mean DCS official or beta release? Just noticed the difference between them. Damn, like a all together new plane in beta. DCS-BIOS doesn't work for the official M2000C, it does however for the beta.

**Comment by Nishizawa145** [comment]
Hi, it's all about open beta. After updating to the newest dcs-fp and dcs-bios. It was also when I had 2.5.5. In m2000 not all worked propperly especially green radio which was changed after razbam update. I think exactly the razbam patch się ale The mess. And about f18, radio panel stoped working after 2.5.6. patch.Wysłano z mojego smartfona Samsung Galaxy.
-------- Oryginalna wiadomość --------Od: Jerker Dahlblom <notifications@github.com> Data: 29.02.2020  18:04  (GMT+01:00) Do: DCSFlightpanels/DCSFlightpanels <DCSFlightpanels@noreply.github.com> DW: Nishizawa145 <pnitendel@gmail.com>, Author <author@noreply.github.com> Temat: Re: [DCSFlightpanels/DCSFlightpanels] M2000C Radio panel (#45) Do you mean DCS official or beta release? Just noticed the difference between them. Damn, like a all together new plane in beta. DCS-BIOS doesn't work for the official M2000C, it does however for the beta.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/DCSFlightpanels/DCSFlightpanels/issues/45?email_source=notifications\u0026email_token=AORAQNXD6VLWU4SHQAK4OWLRFE725A5CNFSM4KTP3MAKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENL7HDY#issuecomment-592966543",
"url": "https://github.com/DCSFlightpanels/DCSFlightpanels/issues/45?email_source=notifications\u0026email_token=AORAQNXD6VLWU4SHQAK4OWLRFE725A5CNFSM4KTP3MAKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENL7HDY#issuecomment-592966543",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jdahlblom** [comment]
Ok thanks. I will check further.

**Comment by WarLord211** [comment]
Here the comparing of the changes there are mad for the radios with the new cockpit 
![2020-04-18](https://user-images.githubusercontent.com/10798954/79635154-8fac2d00-816f-11ea-9a83-6749e10ee2e6.png)

left old / right new cockpit

and here the latest lua:

[M-2000C.zip](https://github.com/DCSFlightpanels/DCSFlightpanels/files/4496455/M-2000C.zip)

**Comment by jdahlblom** [comment]
For me it works, both UHF and VHF presets show correct value in openbeta. UHF was of by 1. Please close this issue if working OK.

**Comment by Nishizawa145** [comment]
Everything works fine now. Closing.
