### ISSUE TITLE
A-10C: standby frequency incorrectly set

### ISSUE THREAD

**Issue by stouset** [DCS-Skunkworks/DCSFlightpanels#46]
When switching frequencies, the decimal portion of the standby frequency (at least on VHF AM) is incorrectly set. If you're switching away from 144.30 (for example), the standby frequency will be set to 144.03.

**Comment by jdahlblom** [comment]
Ok, will have a look at it.

**Comment by jdahlblom** [comment]
Check latest alpha.

**Comment by jdahlblom** [comment]
Fixed. Can you close if OK?

**Comment by stouset** [comment]
Haven’t had a chance to fly in a few days but I’ll let you know on Sunday.

**Comment by jdahlblom** [comment]
Is this OK to close?
