### ISSUE TITLE
F-14 booth Radio presets

### ISSUE THREAD

**Issue by WarLord211** [DCS-Skunkworks/DCSFlightpanels#48]
Since booth Radios goes cracy with the Preset knobs i found the error and eliminate it in BIOS but i think this change affects FP.

Here the changes left old / right new

Pilot
![2020-04-18 (1)](https://user-images.githubusercontent.com/10798954/79635311-866f9000-8170-11ea-9bf0-38dd5f2ec340.png)

RIO
![2020-04-18 (2)](https://user-images.githubusercontent.com/10798954/79635315-87082680-8170-11ea-92a2-41eb6ff8684e.png)

here the new readouts for frequencies:
![2020-04-18 (3)](https://user-images.githubusercontent.com/10798954/79635350-a69f4f00-8170-11ea-88f8-65bc6ba388e3.png)

the lua with this changes 
[F-14B.zip](https://github.com/DCSFlightpanels/DCSFlightpanels/files/4496624/F-14B.zip)

**Comment by jdahlblom** [comment]
Is this official or beta? Which should I use for testing?
And with crazy you mean?

**Comment by WarLord211** [comment]
this is for booth stable and beta.  That was a know bug from the beginning of the F-14.
We had the problem with the preset switch that ist counts false after you go over the 30.

**Comment by jdahlblom** [comment]
OK, changes UHF and VUHF to use the functions for getting the display data.

**Comment by WarLord211** [comment]
fixed in 4.0.11alpha
