### ISSUE TITLE
StreamDeck UI does not show yellow configured dot after clicking `Accept Changes`

### ISSUE THREAD

**Issue by matt-cahill** [DCS-Skunkworks/DCSFlightpanels#49]
Setting up a button for the first time and then clicking `Accept Changes` makes it look like the button lost it's config.

Switching layers makes the yellow dot appear and the config show in the UI.

Alpha 4.0.15

**Comment by jdahlblom** [comment]
Fixed. Can you close if OK?

**Comment by matt-cahill** [comment]
fixed. tested in 4.0.22
