### ISSUE TITLE
Log file in use error on startup when no log file present

### ISSUE THREAD

**Issue by matt-cahill** [DCS-Skunkworks/DCSFlightpanels#51]
Start up with no log file in the run application directory to reproduce

![image](https://user-images.githubusercontent.com/2563358/79721893-3abb1300-8337-11ea-9a21-61cc7ff42ed4.png)

![image](https://user-images.githubusercontent.com/2563358/79721908-41498a80-8337-11ea-8904-409a20b5c37e.png)

**Comment by jdahlblom** [comment]
Check latest alpha.

**Comment by matt-cahill** [comment]
this is resolved
