### ISSUE TITLE
Feature Request: Allow changing StreamDeck button image based on DCS-BIOS data

### ISSUE THREAD

**Issue by matt-cahill** [DCS-Skunkworks/DCSFlightpanels#52]
A simple example of this would be to switch between two images to simulate the flashing of the master caution button.
One image would be the unlit button and the second would be the lit one. Tying this to the output would be something along the lines of a comparison of `if MASTER_CAUTION > 0 then display lit button image`

Where this could make DCSFlightPanels way more powerful than any other current solution would be if it supported greater than two image states.

For example take the 5 position TACAN mode dial in the A-10. If 5 image states were available that entire switch could be controlled and simulated on one button by having an image for each state of the switch and using the increment or sequence output data methods.

**Comment by matt-cahill** [comment]
maki7266 and deep slumber have both requested this feature in chat as well

**Comment by jdahlblom** [comment]
Check latest alpha.

**Comment by jdahlblom** [comment]
This can be closed yeah?

**Comment by matt-cahill** [comment]
yeah i think so, this is implemented and the question of the bit masked output from dcs-bios is something distinct in itself
