### ISSUE TITLE
Feature Request: Allow an image to be the background for DCS-BIOS data image type

### ISSUE THREAD

**Issue by matt-cahill** [DCS-Skunkworks/DCSFlightpanels#53]
Currently only a chosen colour is supported, if an image could be used then making buttons with dynamic data that are recognisable as the thing they represent in the cockpit would be easier.

**Comment by jdahlblom** [comment]
Check latest alpha.

**Comment by jdahlblom** [comment]
Fixed. Can you close if OK?

**Comment by jdahlblom** [comment]
Fixed! Can you close?

**Comment by matt-cahill** [comment]
yes this works as expected, only thing i would ask is could the image and value be initiated on simulation start otherwise it's just black until the dcs-bios output value happens to change?

**Comment by jdahlblom** [comment]
Well that is a bit tricky because the "black box" requires input to produce output. I assume you are referring to the DCS-BIOS Decoder?
A field where you set the start value? I don't know how to select some magic number or string and set it as a start value. Although having a start value would at first seem confusing, "why is that needed".

**Comment by matt-cahill** [comment]
Ah yes hopefully I can explain a bit better, this is for the DCS-BIOS decoder. I don’t mean setting an arbitrary start value.

When DCS starts a mission I believe DCS-BIOS sends a general mission start message. Would it be possible to use that message to trigger a “get all values from DCS-BIOS” action. The values will be there so this should just add another refresh right at the beginning rather than the first refresh being when the value changes from it’s initial state.

In the specific case of data over an image it would be good to have the button background image always display even if there was no data to put on top of it.

**Comment by jdahlblom** [comment]
There is one thing I need to check and that is the variables initialisation value. But that doesn't solve this as a whole.
To be honest I don't remember how DCS-BIOS does it at start. But if it does that then those values will be shown.
I can't query DCS-BIOS for values, whatever is sent in the bytestream is handled and shown.
I will check, might be a bug that is causing what you see.
Do you have any profile for A-10C you could share so I can test?

**Comment by jdahlblom** [comment]
Any difference in latest release (4.0.59_alpha)? 
In the update thread there is a check that the value actually has changed, if not then no screen update is made.
The variables initial value was zero so if the DCS-BIOS control had value zero then no update would have been made.

**Comment by matt-cahill** [comment]
yup this is looking good in 4.0.59
