### ISSUE TITLE
Feature Request: allow cut/copy/paste buttons

### ISSUE THREAD

**Issue by matt-cahill** [DCS-Skunkworks/DCSFlightpanels#57]
From experience it is very common to get half way through designing a profile for the streamdeck and then realise it would work better in another layout. 
Currently the only option is to reprogram from scratch each button in the new layout, which is very time consuming.

Ideal solution: implement cut/copy/paste of buttons and drag and drop of buttons so that buttons swap positions if one is dragged on top of the other.

**Comment by jdahlblom** [comment]
Fixed. Can you close if OK?

**Comment by matt-cahill** [comment]
fixed, tested in 4.0.22
