### ISSUE TITLE
Feature Request: Allow DCS-BIOS string data to be used on streamdeck buttons

### ISSUE THREAD

**Issue by matt-cahill** [DCS-Skunkworks/DCSFlightpanels#59]
For example this would allow a button to have the Hornet or Harrier UFC option displays as its text.

**Comment by jdahlblom** [comment]
I have checked this and there are problems when parsing the DCS-BIOS json files and string functions regarding there are a number of fields that are not populated. I have to examine this further. I've had problems before with the json and it is quite difficult to circumvent (using regex).

**Comment by matt-cahill** [comment]
First iteration of this is working very well. I have seen a couple of issues so far
- the displayed stings are not cleared if the in game string is set to null e.g. hornet scratch pad goes blank after a timeout but the string on the streamdeck is not cleared
- glitching on the button display normally during an update to the string

**Comment by jdahlblom** [comment]
OK, I can't test that. Can you check what CTRL REF shows when it goes blank? 
Glitching, do you mean a partial bitmap is drawn on the OLED? Also check the CTRL REF to descibe to me how that shows the value then too.

**Comment by jdahlblom** [comment]
Check now, any difference?

**Comment by matt-cahill** [comment]
The values clear now when they go from DCS-BIOS 👍 

I can't seem to reproduce the redraw glitch in 4.0.39 so this looks good
