### ISSUE TITLE
UH-1H - UHF frequency band

### ISSUE THREAD

**Issue by WarLord211** [DCS-Skunkworks/DCSFlightpanels#60]
The UHF for the UH-1H Huey is limited in 225.000 Mhz in DCSFP 
In DCS you can actually go down to 200.000 Mhz. 
Any chance to have this corrected? Thanks!

**Comment by jdahlblom** [comment]
Yes, I will fix it.

**Comment by jdahlblom** [comment]
Check latest alpha.
