### ISSUE TITLE
MI-8MT R-863 sync

### ISSUE THREAD

**Issue by WarLord211** [DCS-Skunkworks/DCSFlightpanels#61]
After the rework Radios sync istn working anymore.

Here booth luas: Old and new
[Mi8 luas.zip](https://github.com/DCSFlightpanels/DCSFlightpanels/files/4524560/Mi8.luas.zip)

**Comment by jdahlblom** [comment]
I think this is something we (I) can't fix. Something is off with the Mi-8 module itself.

**Comment by jdahlblom** [comment]
This is OK now oder?

**Comment by WarLord211** [comment]
i think so
