### ISSUE TITLE
BUG F14 Hook Bypass doesn't work

### ISSUE THREAD

**Issue by ZoeESummers** [DCS-Skunkworks/DCSFlightpanels#63]
When mapping a switch to set either 0 or 1 to the HOOK BYPASS on the F14, the cockpit switch doesn't move and the mode doesn't change.

**Comment by WarLord211** [comment]
wich BIOS version do you use? i tested it with the masterbranch of 0.7.xx and there it is working.
(last beta changed some valves)

but anyway i found an bug. that this switch is using the toogle command instad of the switching command
this fix is uploaded

**Comment by ZoeESummers** [comment]
3.6.22 - Latest Release.

**Comment by jdahlblom** [comment]
I will see if I find anything.

**Comment by WarLord211** [comment]
@Zoe 
thats no BIOS version there is 0.7.XX or The BIOS HUB versions 0.9 and higher

**Comment by jdahlblom** [comment]
OK so issue is solved by using latest DCS-BIOS version if I understand Warlord correctly.

**Comment by jdahlblom** [comment]
@ZoeESummers  any info regarding this? Was it the DCS-BIOS version?

**Comment by ZoeESummers** [comment]
Hi. Sorry for being AWOL; I’ve not been well. 

I haven’t installed dcs-bios separately. I have Helios installed as well as dcs flight panels. I do get a big grey warning box when I start this version of flight panels and it mentions dcs-bios, but I’m unsure what to do. 

Sorry.

**Comment by WarLord211** [comment]
Flightpanels dont work without BIOS!

**Comment by ZoeESummers** [comment]
Fixed it. I seemed to have most but not all of DCS BIOS installed as most of the bindings worked - just not the hook. Anyway I fixed it and cleared out the error log manually and now even the warning doesn't come up. 

Thanks for all the help.
