### ISSUE TITLE
BUG: bitmasks not applied to dcs-bios output for streamdeck

### ISSUE THREAD

**Issue by matt-cahill** [DCS-Skunkworks/DCSFlightpanels#67]
As an example the A-10 master caution light output, `MASTER_CAUTION`, when configuring the PZ55 panel LEDs reports a `0` for OFF and `1` for ON. However in the streamdeck UI for configuring button images the output appears as `16416` for OFF and `18464` for ON.

Included is a test profile to illustrate

[A-10_StreamDeck_Master_Caution_Example.zip](https://github.com/DCSFlightpanels/DCSFlightpanels/files/4573942/A-10_StreamDeck_Master_Caution_Example.zip)

**Comment by jdahlblom** [comment]
Yes confirmed. I fixed it yesterday but started getting loads of exceptions from the DCS-BIOS library when masking etc. Have to examine further.

**Comment by matt-cahill** [comment]
fixed in 4.0.52
