### ISSUE TITLE
Pressing "Save" on DCSFlightpanels causes crashes in VKB Dev CFG

### ISSUE THREAD

**Issue by Andytr1** [DCS-Skunkworks/DCSFlightpanels#69]
DCS Flight panels version 64_3.6.22. 
Open it, make any changes to PZ55 profile and press save.
Attempt to open VKBDEVCFG (software used by VKB joystick configuration utility). The software will become unresponsive and crash shortly. Even closing out of DCS Flight panels doesn't allow VKB DEV CFG to work.
I have to restart my machine.

**Comment by jdahlblom** [comment]
Well all it does it saves the file. Some Events are sent internally in DCSFP and the various panels reloads the settings from the file.
The only thing I can see is that you have some settings in DCSFP relating to VKB and that somehow is executed.
