### ISSUE TITLE
Feature Improvement: Export images alongside button export metadata

### ISSUE THREAD

**Issue by matt-cahill** [DCS-Skunkworks/DCSFlightpanels#70]
In order to facilitate easier sharing of streamdeck profiles within the DCSFP user community a simple way to include or link the required images for a profile is requested.

As there is already a metadata import/export feature it makes sense to augment this to collect together all the referenced images in a profile into one folder on export and provide a simple way to automatically re-link the images with the buttons on import.

Design wise I imagine something along these lines

- On Export:
  - DCSFP produces a folder containing the json formatted text file and all images.
  - the exported image paths would be re-written to their relative path in the collection.
- Considerations here would be
  - image file name conflicts - sub folders for each button maybe or append an instance number or rename based on function?
  - do not include images that are already included with DCSFP e.g. home button image
  - de-duplication of images i.e. if the same image is used multiple times only include (collect) it once and reference it multiple times in the metadata

- Sharing
  - This folder could then easily be zipped up and transferred or committed to a git repo or similar.

- On Import:
  - The user selects either the shared folder or the json file inside the folder (whichever makes more sense) to start the import process.
  - DCSFP would initially look in the same folder for the images i.e. use the containing folder of the json file as the root of the relative image file paths contained within the export file.
  - IF the FIRST image looked for by DCSFP is not found the user could be asked for the location of the folder containing the images. 
  - Otherwise any subsequent failures could be handled in one of two ways:
    - Ask for the location of each missing file or offer to skip
    - Skip all missing files and notify at the end letting the user re-link them in the UI manually.

Hope that makes sense @jdahlblom? Can discuss further on Discord.

**Comment by matt-cahill** [comment]
- is it possible to handle import to multiple layers at once or to include the layer name in the import button list? Currently only way to know what button goes where is to do separate exports per layer.
- Image path corruption for paths inside the dcs-bios decoder section missing `\` between image name and containing folder
![image](https://user-images.githubusercontent.com/2563358/81900659-661cdf00-9611-11ea-800f-40b19a7a80c3.png)
- If you import a button that uses an image of the same name as an existing button image you get the following error
```14.05.2020 06:40:08  version : 1.0.256.4835

System.IO.IOException
The process cannot access the file '..\DCSFlightPanelsProfiles\import_test\dialdown.png' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at DCSFlightpanels.Windows.StreamDeck.ImportWindow.CopyImagesToNewLocation()
   at DCSFlightpanels.Windows.StreamDeck.ImportWindow.ButtonImport_OnClick(Object sender, RoutedEventArgs e)
```
![image](https://user-images.githubusercontent.com/2563358/81901274-59e55180-9612-11ea-8116-c716b409901d.png)

**Comment by matt-cahill** [comment]
results of my import testing can be found here:
https://github.com/matt-cahill/DCSFlightPanelsProfiles/tree/StreamDeck_Import_Testing

the source profile was this one
https://github.com/matt-cahill/DCSFlightPanelsProfiles/blob/StreamDeck/F-16_StreamDeck.bindings

**Comment by matt-cahill** [comment]
Making a new folder in the image destination dialog and naming it keeps the name "New Folder" and results in an I/O error

```
14.05.2020 06:50:13  version : 1.0.256.4835

System.IO.DirectoryNotFoundException
Could not find a part of the path '..\DCSFlightPanelsProfiles\New folder\0.png'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at DCSFlightpanels.Windows.StreamDeck.ImportWindow.CopyImagesToNewLocation()
   at DCSFlightpanels.Windows.StreamDeck.ImportWindow.ButtonImport_OnClick(Object sender, RoutedEventArgs e)
```

![image](https://user-images.githubusercontent.com/2563358/81902191-d4fb3780-9613-11ea-9bf0-2e1c5622bb60.png)

subsequent re-selection of the image folder results in a path like this
```
"ImageFile": "..\\DCSFlightPanelsProfiles\\f18_import\\..\\DCSFlightPanelsProfiles\\New folder\\symbrt.png",
```

**Comment by matt-cahill** [comment]
It is possible to import buttons with dcs-bios data for an airframe that does not match the airframe of the profile.
e.g. can import F16 buttons into an F18 profile

**Comment by jdahlblom** [comment]
> It is possible to import buttons with dcs-bios data for an airframe that does not match the airframe of the profile.
> e.g. can import F16 buttons into an F18 profile

Yes and it will produce (should) errors afterwards.

**Comment by jdahlblom** [comment]
> 
> 
> Making a new folder in the image destination dialog and naming it keeps the name "New Folder" and results in an I/O error
> 
> ```
> 14.05.2020 06:50:13  version : 1.0.256.4835
> 
> System.IO.DirectoryNotFoundException
> Could not find a part of the path '..\DCSFlightPanelsProfiles\New folder\0.png'.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
>    at DCSFlightpanels.Windows.StreamDeck.ImportWindow.CopyImagesToNewLocation()
>    at DCSFlightpanels.Windows.StreamDeck.ImportWindow.ButtonImport_OnClick(Object sender, RoutedEventArgs e)
> ```
> 
> ![image](https://user-images.githubusercontent.com/2563358/81902191-d4fb3780-9613-11ea-9bf0-2e1c5622bb60.png)
> 
> subsequent re-selection of the image folder results in a path like this
> 
> ```
> "ImageFile": "..\\DCSFlightPanelsProfiles\\f18_import\\..\\DCSFlightPanelsProfiles\\New folder\\symbrt.png",
> ```

I don't understand that. Please explain in details how this happens.

**Comment by jdahlblom** [comment]
Please create new issues if you find more bugs regarding export & import. Thanks.

**Comment by matt-cahill** [comment]
> is it possible to handle import to multiple layers at once or to include the layer name in the import button list? Currently only way to know what button goes where is to do separate exports per layer.

working in v4.0.64

**Comment by matt-cahill** [comment]
> Image path corruption for paths inside the dcs-bios decoder section missing \ between image name and containing folder

working in v4.0.64

**Comment by matt-cahill** [comment]
> If you import a button that uses an image of the same name as an existing button image you get the following error

working in v4.0.64

**Comment by matt-cahill** [comment]
> Making a new folder in the image destination dialog and naming it keeps the name "New Folder" and results in an I/O error

will split this into it's own issue

**Comment by matt-cahill** [comment]
I would consider this implemented now so i will close this and raise any issues separately.
