### ISSUE TITLE
Image import destination folder path error

### ISSUE THREAD

**Issue by matt-cahill** [DCS-Skunkworks/DCSFlightpanels#73]
The original error in 4.0.62 was like this however the behavior has improved in 4.0.64.

------------------------------------
Making a new folder in the image destination dialog and naming it keeps the name "New Folder" and results in an I/O error

```
14.05.2020 06:50:13  version : 1.0.256.4835

System.IO.DirectoryNotFoundException
Could not find a part of the path '..\DCSFlightPanelsProfiles\New folder\0.png'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at DCSFlightpanels.Windows.StreamDeck.ImportWindow.CopyImagesToNewLocation()
   at DCSFlightpanels.Windows.StreamDeck.ImportWindow.ButtonImport_OnClick(Object sender, RoutedEventArgs e)
image
```

subsequent re-selection of the image folder results in a path like this

```
"ImageFile": "..\\DCSFlightPanelsProfiles\\f18_import\\..\\DCSFlightPanelsProfiles\\New folder\\symbrt.png",
```
------------------------------------

In 4.0.64 the two paths are no longer concatenated but it is still possible to get a path containing `New folder` instead of the actual name of the created folder. Steps to reproduce:

This only happens if the destination of the new folder is not open in a File Explorer at the same time,

1. Start an import using an export file that contains images
1. In the image folder box click `Browse...`
1. Choose a suitable path and then click `Make New Folder`
1. Type in a name BUT do not press enter
1 Press `OK`

You should end up with a path like this `..\\DCSFlightPanelsProfiles\\New folder` in the Image Folder box but the actual name of the folder on disk will be whatever you typed in.

**Comment by matt-cahill** [comment]
I'm wondering if this is a windows bug seeing as it works correctly when the containing folder is open in File Explorer at the same time.

**Comment by jdahlblom** [comment]
Yeah it could be a Windows thing. I will disable the New Folder in the dialog.

**Comment by jdahlblom** [comment]
Now that the button is disabled you can only create the folder via the right click context menu. 
BUT if you rename the folder and while renaming presses Enter then the text will revert to "New Folder". You can just see it before the dialog closes.

**Comment by jdahlblom** [comment]
Close issue?

**Comment by jdahlblom** [comment]
Close issue?
