### ISSUE TITLE
White squares instead of chosen pictures on streamdecks

### ISSUE THREAD

**Issue by BSDBaDCrC** [DCS-Skunkworks/DCSFlightpanels#76]
When the picture to display is associated to a dcs-bios variable (like a LED value), loading the profile displays white squares instead of the said pictures. The affected buttons are random. Each re initialization of DCS FP (latest 4.0.68) displays white squares on different buttons. Sometimes the pictures shows back up when the variable is initialized by DCS. Sometimes it always stays white.
Using Ka-50 profile
Pics are .png
I have SD 15, SD 32XL and SD 6 Mini connected at the same time.
Assigning a fixed pic to a buttons works without a problem. Only dynamic ones are a problem.

![20200607_005322](https://user-images.githubusercontent.com/66567652/83976575-c1688700-a8c8-11ea-9dda-c42e17c99505.jpg)
![20200607_005014](https://user-images.githubusercontent.com/66567652/83976579-c7f6fe80-a8c8-11ea-9c88-12009b83b9ab.jpg)

**Comment by jdahlblom** [comment]
OK I have to look into this. Perhaps user can specify some default image if now data is available from DCS-BIOS.

**Comment by jdahlblom** [comment]
Is this OK in 4.0.75 ?

**Comment by BSDBaDCrC** [comment]
Looks good now. Thanks
