### ISSUE TITLE
Stretched pics

### ISSUE THREAD

**Issue by BSDBaDCrC** [DCS-Skunkworks/DCSFlightpanels#77]
A picture that is not square will stretched across the button and look strange. (see flip switch)
![20200607_005322](https://user-images.githubusercontent.com/66567652/83976612-13a9a800-a8c9-11ea-85b8-fc9dde4aaa8b.jpg)

**Comment by jdahlblom** [comment]
Does this same image look OK with Stream Deck official software?

**Comment by jdahlblom** [comment]
?

**Comment by BSDBaDCrC** [comment]
Yes. The switch picture is showing normally in SD software. Note that I can simply edit my picture to make it square instead.

**Comment by jdahlblom** [comment]
Please send me a picture some sample pictures for testing.

**Comment by jdahlblom** [comment]
Is this OK now?

**Comment by BSDBaDCrC** [comment]
Yes!
