### ISSUE TITLE
Name of actions not saved

### ISSUE THREAD

**Issue by BSDBaDCrC** [DCS-Skunkworks/DCSFlightpanels#78]
When creating an action and leaving the name field empty, DCSFP will by default name the action DCS-BIOS (assuming you chose DCS-BIOS for the action). But if you are trying to name the action, the name will not be saved and the action will still be named DCS-BIOS.

**Comment by jdahlblom** [comment]
OK will check.

**Comment by jdahlblom** [comment]
On any specific panel?

**Comment by WarLord211** [comment]
Duplicate of #83

**Comment by WarLord211** [comment]
its solved in 4.1.12
