### ISSUE TITLE
Variables not received on some SD

### ISSUE THREAD

**Issue by BSDBaDCrC** [DCS-Skunkworks/DCSFlightpanels#79]
I guess this one is hard because depending on the streamdeck, behavior is different.
I mostly have not too many issues with the XL but the 15 buttons and the mini are another story.
The std doesn't seem to properly receive the values of a given variable. I am using the Ka-50 profile. When programming the exact same output on the XL, I can see the variable value (LED) going from zero to one alright. With the exact same button on the SD standard, it doesn't show any change in the variable value, but it does change it on the twin button of the XL.  Can it be a problem with SD being on a USB hub?

**Comment by jdahlblom** [comment]
OK yeah that is weird.
Although the UI differs the code behind is the same. So check that with the hub (good observation!) and report back. Really weird.

**Comment by jdahlblom** [comment]
Is still this a problem?
