### ISSUE TITLE
SD Mini appearing like a SD 15 buttons on DCSFP

### ISSUE THREAD

**Issue by BSDBaDCrC** [DCS-Skunkworks/DCSFlightpanels#80]
The mini is showing up on DCSFP as a 15 buttons. What makes thing harder is that the order of the buttons are not how they look like in real life. 
![Minivsstd1](https://user-images.githubusercontent.com/66567652/83976885-f37ae880-a8ca-11ea-91ad-0ee9ece6150f.jpg)

One would expect that the mini's 1,2,3 buttons will be the std's 1,2,3 buttons (and it is)
But the mini's 4,5,6 are not std 6,7,8 but also 4,5,6 which is not very intuitive.

**Comment by jdahlblom** [comment]
Is this OK in 4.0.75?

**Comment by jdahlblom** [comment]
Has this been solved? If so please close this issue.

**Comment by BSDBaDCrC** [comment]
Ah, didn't know I had to close. Yes. Issue solved! Thanks!
