### ISSUE TITLE
[Feature Request] Layers control from a second SD

### ISSUE THREAD

**Issue by BSDBaDCrC** [DCS-Skunkworks/DCSFlightpanels#81]
Would love to be able to control whatever layer of StreamDeck A from StreamDeck B.
For example, I can press one button of my SD mini to switch the display of my SD 15 to show the Ka50 LWS instead of the PVI800.

**Comment by jdahlblom** [comment]
SD Mini ordered today, will implement this once it arrives.

**Comment by BSDBaDCrC** [comment]
Awesome! Thanks man!
