### ISSUE TITLE
Flightpanels Main Panel not remembering window size

### ISSUE THREAD

**Issue by scotflieger** [DCS-Skunkworks/DCSFlightpanels#82]
Every time I open Flightpanels (DCSFP.exe) I have to reduce the window width to fit on a secondary monitor. This does not require any overlapping of elements on the window.
The default width should be set to that of the panels graphics and the right column. 

![dcsfp](https://user-images.githubusercontent.com/8685475/84240258-a75fbc00-aaf5-11ea-8382-7df33eddd394.jpg)

**Comment by jdahlblom** [comment]
OK will check.

**Comment by jdahlblom** [comment]
Yes found it. Will be in next release.

**Comment by BSDBaDCrC** [comment]
Actually, if I may, it's not only about the size but also the last position used. Same for me and my 5 screens. DCSFP always shows up first on the primary screen and I have to drag and resize it everytime, which is not the case of all the other softwares I am using for DCS (like Helios, SRS,...)

**Comment by jdahlblom** [comment]
OK yeah. I have been oogling this and I am stumped. I can't get it working. I will check later again.

**Comment by scotflieger** [comment]
Window size and position remembered. Great work thank you.

**Comment by WarLord211** [comment]
confirmed
