### ISSUE TITLE
Random stream of keystrokes on first use of a Switch Panel.

### ISSUE THREAD

**Issue by ZoeESummers** [DCS-Skunkworks/DCSFlightpanels#84]
I have TWO Switch Panels.

I'm using keystrokes for an Elite Dangerous profile.

I have unique keybindings on each switch panel.

When I first launch this application and I load this profile, on the first use of a switch or a button on ONE of the two panels it sends a stream of characters (seemingly random).

After it's had it's 'hissy fit' it works fine and correctly for all the assigned keystrokes, until you close and relaunch this application again and it does the same. 

I feel this might be because I'm using two of the same 'type' of Saitek pro panels. 

![unknown](https://user-images.githubusercontent.com/2620349/85185822-9a796000-b28d-11ea-9029-9385777fe818.png)

You can see in the output window of this image, that after loading this profile I tested a few buttons on one panel, switched to the second then a stream of keystrokes happened, then this panel worked fine afterwards.

**Comment by jdahlblom** [comment]
The reason for this that DCSFP has no way of knowing the switch's / dial position before there are any output from the panel.
1) User start DCSFP, DCSFP registers the panels that are connected but knows nothing about which button is in which position.
2) User change one dial / switch
3) With that (USB/HID) Report all buttons and dials are reported, their position.
4) DCSFP acts accordingly

I will look at the code and see what can be done.

**Comment by jdahlblom** [comment]
So the switch panel (PZ55) seems to send differently, many sequential HID reports. Ah btw it can be related to the library too handling this stuff. Noticed the report is the same.
