### ISSUE TITLE
Error when opening profile after changing USB port for one panel

### ISSUE THREAD

**Issue by ZoeESummers** [DCS-Skunkworks/DCSFlightpanels#86]
I understand you have a hack/workaround by clicking the ID button to copy it to the clipboard and then you have to manually replace that in the profile. 

It isn't this simple however if you have two panels that are the same type. i.e. two Saitek Switch Panels.

You have no way to identify which of the two panels in the text file belongs to the one that is on a new USB port.

This application should handle port switching gracefully with no user interaction. 

Thanks.

**Comment by jdahlblom** [comment]
Check #87, can't be done when there are multiples of same panel though. Will do something though to help the user.
