### ISSUE TITLE
[feature request]: Consider decoupling sets of config from specific USB hardware IDs

### ISSUE THREAD

**Issue by matt-cahill** [DCS-Skunkworks/DCSFlightpanels#87]
When the physical configuration of panels changes on the host computer the USB IDs change. The flight panels app automatically detects all the panels present, but the sets of config previously assigned to specific panels then need to be manually re-mapped to their original panels by copying the ID provided by the app into the configuration file.

Solving this when only one instance of a particular panel type is present should be easy just assign the applicable config set to the matching panel type and warn the user if there is config for a panel type that doesn’t exist. However if there are multiple panels of the same type this can no longer be done.

As a result I propose storing these sets of configurations using a generic instance ID e.g. `PZ55#01` And then implementing a drop down on each tab allowing the user to assign the config set of choice to whichever panel they need via the UI.

**Comment by jdahlblom** [comment]
Yeah that could be a solution to it.
