### ISSUE TITLE
[UI/UX Issues] relating to clicking, double-clicking and editing DCS BIOS bindings 

### ISSUE THREAD

**Issue by ZoeESummers** [DCS-Skunkworks/DCSFlightpanels#88]
Is there a way you can clean up and use standard idioms instead of confusing ones when binding DCS BIOS to a switch please? 

E.g. 

In all Windows based OS's e.g. macOS, Windows, Linux, a double click event allows you to edit an existing entry e.g. think of excel, however, in DCSFlightPanels it deletes a binding if done at the highest level, but then does nothing once you are in the 'detail' view of a switch binding to a DCS BIOS entry. 

Here you have to click 'EDIT' on the right side to edit an existing binding, where double-clicking would be common parlance. 

Because of these "broken" UX paradigms, every time I have to rebuild a profile (because of either a bug I've already reported, or because the ID's have changed and I have two panels of the same type) then I waste so much time working 'around' or fighting with the UI instead of it letting me bind things much more efficiently and with standard windows/mouse paradigms. 

Thanks for reading, I hope I explained adequately

**Comment by jdahlblom** [comment]
@ZoeESummers, what do you suggest instead in regards of the text boxes in the UI where the action is shown to the user?
There are tons of settings and those text boxes are the fastest way of e.g. entering a new key press.
Give me a bullet list containing each thing you think could be done better.

**Comment by jdahlblom** [comment]
OK thanks, I will check this out.

**Comment by jdahlblom** [comment]
Yup, I will implements some or all of this.

**Comment by jdahlblom** [comment]
@ZoeESummers  You can reach me via our Discord Server.

**Comment by jdahlblom** [comment]
>     7. A great point is that you have too many steps to bind a DCS control. The intermediate window is kinda pointless as the final control window where you search for and then set a value to a specific binding is really all you need, esp if inside there was the 'Description field' that populated the main display was pre-populated with the existing 'Control Description' so we don't have to type it out again or copy/paste.
You can use multiple DCS-BIOS commands and that is why it is made like that. Sequence for enabling certain navigation or weapons system etc.

**Comment by jdahlblom** [comment]
Damn it, one snag. I don't own the TPM so then it would leave that with the old way of interacting. That won't do, it would be super confusing. Can't make changes to the TPM as I can't debug it. Used to own it but gave it away long time ago.

**Comment by ZoeESummers** [comment]
TPM?

**Comment by ZoeESummers** [comment]
Can we not work together in a branch we’re I or other who do have it can test it out and report back to you? I’m happy to test if it would help. Or you know, buy it from Amazon and return it within 14 days.... just sayin’ ;)

**Comment by jdahlblom** [comment]
Please contact me on https://discord.gg/5svGwKX via DM. (ArturDCS)
