### ISSUE TITLE
DCSFlightpanels not working as a standalone 

### ISSUE THREAD

**Issue by brianjgregory** [DCS-Skunkworks/DCSFlightpanels#90]
I am really impressed with the DCS Flight Panels software, hence my recent donation. I had been about to give up on the Saitek/Logitech PZ55 switch panel, due to its utility being limited to just FSX, X-Plane & Prepar3D; none of which I play very often nowadays. I now have ability to use it with the DCS variants, and with IL-2, IL-2 CoD, -BoS & variants etc. 

I have one query. Does DCS/ DCS World have to be installed for the DCS Flightpanel software to be usable in Keyboard Emulation mode? As an alternative, can the DCS Flightpanels software possibly be misled into thinking DCS is installed even if isn't?   

DCSFlightpanels works fine on my main SSD, where I do have DCS installed. I also have a smaller, old SSD on which I run Windows 7.0, so I can still play Battle of Britain II; which doesn't work well under Windows 10. This SSD is only 80Gb; with 40Gb free after installing Windows & BoBII; so I can't fit DCS World on it. I have installed DCS-BIOS & DCSFlightpanels exactly as on my main SSD. The panel is detected as the three green Gear Lowered LEDs are iluminated, but the software is unresponsive to gear lever position change (except that When I try to programme any commands, or move the gear selector, I get a notification: "Method not found:'!!0[]System.Array.Empty()'" Any advice on solving this problem would be appreciated. Thanks, Brian 
[DCSFlightpanels_error_log.txt](https://github.com/DCSFlightpanels/DCSFlightpanels/files/4875379/DCSFlightpanels_error_log.txt)
Gregory.

**Comment by jdahlblom** [comment]
DCSFlightpanels should work without DCS as key emulator. That is the goal. BUT  due to the heavy DCS focus it has happened that I've introduced dependencies that shouldn't be. I have to check that it works properly again.

**Comment by jdahlblom** [comment]
>The panel is detected as the three green Gear Lowered LEDs are iluminated, but the software is unresponsive to gear lever position change (except that When I try to programme any commands, or move the gear selector, I get a notification: "Method not found:'!!0[]System.Array.Empty()'"

Can you post a bullet list the steps you take and what happens / does not happen, I don't fully understand your explanation. 

Software is unresponsive to what?
Only the gear selector is working?
Does the problem computer have all Windows Updates applied?
Is .NET Framework 4.7 installed?

**Comment by jdahlblom** [comment]
I renamed my ```C:\Users\<user>\Saved Games\DCS``` folder, this way DCSFP can't see DCS-BIOS or anything else relating to DCS. I can't reproduce those problems. What else could I do to reproduce your errors?

**Comment by brianjgregory** [comment]
Sorry been out of circulation, press-ganged into garden tidying projects by my better half. I have uninstalled DCSBIOS on my Windows 7 drive as DCS is not installed. I will upgrade to .NET 4.07, as suspect the current is 3.0 something, as I haven't updated W7 for aeons; not wanting it to start trying to upgrade to 10. The DCSFlightpanels software registers the same warning (shown in the previously attached error log, when I try to enter any keystroke, , move the gear selector lever or open any profile. I will report back after trying the steps you've recommended. Thanks, Brian Gregory.

**Comment by jdahlblom** [comment]
Was this OK then after updating the .NET framework? Issue can be closed?
