### ISSUE TITLE
Logitech G Pro Flight Radio Panel - decor use for arcade cabinet

### ISSUE THREAD

**Issue by statiktrax** [DCS-Skunkworks/DCSFlightpanels#93]
This is probably a question you've never gotten and I've already searched hours trying to solve it myself. Finally I was directed here and seeing that this hub is active, fingers crossed someone can help. I'm more than happy to tip if you can solve my headache for this hurdle I'm dealing with.

Here's the issue. I purchased this device NOT for use for any flight sim game it was used for. I thought I would be able to plug the usb in and control the numbers manually physically on the device by the dials. Nope. I realize I need a flight sim game running to do this. I need a work around. A hack of some sort. Maybe a program that runs low resource in background tricked into thinking its on? 

What's this for you ask? I'm working on a custom arcade cabinet, it's actually the Star Wars Arcade1up sit down cabinet but I've re-themed mine into a modded Star Fox machine. The control panel yoke was re-angled so now I have a dashboard area. Since Star Fox has a heavy theme dialogue of radio controls I thought this device would be perfect for the aesthetic in that area. All I want to do is control the dial numbers manually to whatever I want. No in game functionality required. 

And no test mode sucks. That's just a lame countdown that doesn't pass what I'm hoping for.

Can we do this? Please hit me up soon and thanks for reading.

**Comment by jdahlblom** [comment]
No not interested, good luck with the project though!
