### ISSUE TITLE
DCS-BIOS json Error

### ISSUE THREAD

**Issue by Gunpilot** [DCS-Skunkworks/DCSFlightpanels#94]
Hello,

I'm trying to get this DCS Flightpanels and DCS Bios to work but every time I load Flight Panels I get an error saying my user.config is no good as well as Error loading DCS-BIOS. check that the DCS-BIOS location setting points to the JSON directory.

the details logged say: 

Could not find 'C:\Users\ME\Saved Games\DCS\Scripts\dcs-bios\doc\CommonData.josn'. at System.IO.__Error.WinIOError(int32 errorCode, String maybeFullPath)

as well as a slew of other things.

How do I get the JSON directory?  I'm sorry I'm not super computer savvy, but I'm trying to get this working!  

Thank you for your time.

**Comment by WarLord211** [comment]
BIOS Version?
BIOS Installed in version of DCS you want to use (stable/beta)?

You may concider our DIscord:
https://discord.gg/5svGwKX

**Comment by jdahlblom** [comment]
Do you intend to you DCS-BIOS or use DCSFP as pure key emulator? If DCS-BIOS, have you verified it is working as per our Wiki? DCSFP needs to know where the json files for DCS-BIOS is stored as it uses them to know what airplane controls exists.

**Comment by Gunpilot** [comment]
Sorry I didn't get back with you sooner.  I was out of town for work.
I planned on trying to use the DCSFP in conjunction with my Logitech G-Pro radio panel, multi panel, and switch panel.
I did get the multi panel to show up once on the DCSFP.  But it still keeps giving me the error when I try to load it.  
I'll try to jump on the Discord thread later on today.
Thanks for getting back to me.
Max
    On Thursday, July 30, 2020, 12:16:58 AM MDT, Jerker Dahlblom <notifications@github.com> wrote:  
 
 


Do you intend to you DCS-BIOS or use DCSFP as pure key emulator? If DCS-BIOS, have you verified it is working as per our Wiki? DCSFP needs to know where the json files for DCS-BIOS is stored as it uses them to know what airplane controls exists.

**Comment by jdahlblom** [comment]
Is this still a problem?
