### ISSUE TITLE
-nostreamdeck parameter not working

### ISSUE THREAD

**Issue by da-drake** [DCS-Skunkworks/DCSFlightpanels#95]
I've added the -nostreamdeck parameter to my shortcut, but I'm still receiving a warning that StreamDeck's official software is running in the background. 

Shortcut target: "C:\Users\Drake\Saved Games\DCSFlightpanels_x64_4.1.12\dcsfp.exe" -nostreamdeck

I've tried launching from the command prompt with the below command, but still received the warning. 

"c:\Users\Drake\Saved Games\DCSFlightpanels_x64_4.1.12\dcsfp.exe" -nostreamdeck

I thought maybe the quotes (due to the spaces in "Saved Games") might be an issue so I launched with the below command, but still received the warning. 

c:\Users\Drake\SAVEDG~1\DCSFlightpanels_x64_4.1.12\dcsfp.exe -nostreamdeck

**Comment by da-drake** [comment]
Ok, so I found out the parameter is case sensitive. Under the stream deck article in the wiki it is presented as "-nostreamdeck", but under the command line parameters article it is "-NoStreamDeck". Looks like the documentation just needs to be updated/corrected.

**Comment by ereidelbach** [comment]
@da-drake Great find.  I came here to report this issue and found your solution instead.  Thank you!

**Comment by jdahlblom** [comment]
Thanks, I will update the wiki and also make sure the parameters works in whichever case they are used.

**Comment by jdahlblom** [comment]
Fixed in 4.1.14 release.
