### ISSUE TITLE
Fuel Pump switch inop on PZ55

### ISSUE THREAD

**Issue by BSDBaDCrC** [DCS-Skunkworks/DCSFlightpanels#98]
Became intermittent then stopped working completely. Tried with a brand new PZ 55 and still the problem persists. Now I have two PZ55 :-P

**Comment by jdahlblom** [comment]
Is this DCS-BIOS related (only)?

**Comment by BSDBaDCrC** [comment]
I don't know. My first guess was that my PZ55 was deficient. But after buying a brand new PZ55, the same switch is still inop. This can't be happening to two PZ55 in  row.

**Comment by jdahlblom** [comment]
No I mean is it DCS-BIOS that you have it configured to? Not key emulation?

**Comment by BSDBaDCrC** [comment]
Whether I am loading a DCS BIOS or a Key emulation blank profile, the switch keeps being unresponsive or at best unreliable. Looks like a USB issue maybe  more than a software one. But why and what changed. This is puzzling

**Comment by jdahlblom** [comment]
I will close this. Adding that Logitech's own software showed the same results. So there is something wrong with the panels  / Windows 10.
