### ISSUE TITLE
Unable to toggle back to 'Generic Radio Panel' 

### ISSUE THREAD

**Issue by ZoeESummers** [DCS-Skunkworks/DCSFlightpanels#99]
If you have an existing and working profile that doesn't include the radio panel, then buy and connect a radio panel, it will automatically add it as a non-generic platform specific panel. This may not be what the user requires, and there is no 'built in' way to revert that radio panel back to generic.

**Comment by jdahlblom** [comment]
OK, will have to check that. Thanks.
